/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Mcp_clientRouteImport } from './routes/mcp_client'
import { Route as IndexRouteImport } from './routes/index'

const Mcp_clientRoute = Mcp_clientRouteImport.update({
  id: '/mcp_client',
  path: '/mcp_client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp_client': typeof Mcp_clientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp_client': typeof Mcp_clientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp_client': typeof Mcp_clientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mcp_client'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mcp_client'
  id: '__root__' | '/' | '/mcp_client'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Mcp_clientRoute: typeof Mcp_clientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp_client': {
      id: '/mcp_client'
      path: '/mcp_client'
      fullPath: '/mcp_client'
      preLoaderRoute: typeof Mcp_clientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Mcp_clientRoute: Mcp_clientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
